// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.HandleException;

import java.time.LocalDateTime;
import org.springframework.http.HttpStatus;

public class ApiError {
    private String message;
    private HttpStatus httpStatus;
    private LocalDateTime timeStamp;

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public HttpStatus getHttpStatus() {
        return this.httpStatus;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getTimeStamp() {
        return this.timeStamp;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setHttpStatus(final HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimeStamp(final LocalDateTime timeStamp) {
        this.timeStamp = timeStamp;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ApiError)) return false;
        final ApiError other = (ApiError) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$httpStatus = this.getHttpStatus();
        final java.lang.Object other$httpStatus = other.getHttpStatus();
        if (this$httpStatus == null ? other$httpStatus != null : !this$httpStatus.equals(other$httpStatus)) return false;
        final java.lang.Object this$timeStamp = this.getTimeStamp();
        final java.lang.Object other$timeStamp = other.getTimeStamp();
        if (this$timeStamp == null ? other$timeStamp != null : !this$timeStamp.equals(other$timeStamp)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ApiError;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $httpStatus = this.getHttpStatus();
        result = result * PRIME + ($httpStatus == null ? 43 : $httpStatus.hashCode());
        final java.lang.Object $timeStamp = this.getTimeStamp();
        result = result * PRIME + ($timeStamp == null ? 43 : $timeStamp.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ApiError(message=" + this.getMessage() + ", httpStatus=" + this.getHttpStatus() + ", timeStamp=" + this.getTimeStamp() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ApiError(final String message, final HttpStatus httpStatus, final LocalDateTime timeStamp) {
        this.message = message;
        this.httpStatus = httpStatus;
        this.timeStamp = timeStamp;
    }
}
