// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.dto;

public class ContoBancaDto extends ContoDto {
    String iban;


    @java.lang.SuppressWarnings("all")
    public static abstract class ContoBancaDtoBuilder<C extends ContoBancaDto, B extends ContoBancaDto.ContoBancaDtoBuilder<C, B>> extends ContoDto.ContoDtoBuilder<C, B> {
        @java.lang.SuppressWarnings("all")
        private String iban;

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B iban(final String iban) {
            this.iban = iban;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ContoBancaDto.ContoBancaDtoBuilder(super=" + super.toString() + ", iban=" + this.iban + ")";
        }
    }


    @java.lang.SuppressWarnings("all")
    private static final class ContoBancaDtoBuilderImpl extends ContoBancaDto.ContoBancaDtoBuilder<ContoBancaDto, ContoBancaDto.ContoBancaDtoBuilderImpl> {
        @java.lang.SuppressWarnings("all")
        private ContoBancaDtoBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected ContoBancaDto.ContoBancaDtoBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public ContoBancaDto build() {
            return new ContoBancaDto(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    protected ContoBancaDto(final ContoBancaDto.ContoBancaDtoBuilder<?, ?> b) {
        super(b);
        this.iban = b.iban;
    }

    @java.lang.SuppressWarnings("all")
    public static ContoBancaDto.ContoBancaDtoBuilder<?, ?> builder() {
        return new ContoBancaDto.ContoBancaDtoBuilderImpl();
    }

    @java.lang.SuppressWarnings("all")
    public ContoBancaDto(final String iban) {
        this.iban = iban;
    }

    @java.lang.SuppressWarnings("all")
    public ContoBancaDto() {
    }

    @java.lang.SuppressWarnings("all")
    public String getIban() {
        return this.iban;
    }

    @java.lang.SuppressWarnings("all")
    public void setIban(final String iban) {
        this.iban = iban;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ContoBancaDto)) return false;
        final ContoBancaDto other = (ContoBancaDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$iban = this.getIban();
        final java.lang.Object other$iban = other.getIban();
        if (this$iban == null ? other$iban != null : !this$iban.equals(other$iban)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ContoBancaDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $iban = this.getIban();
        result = result * PRIME + ($iban == null ? 43 : $iban.hashCode());
        return result;
    }
}
