// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.dto;

import java.util.Set;

public class ContoDto {
    Integer id;
    UserDto userDto;
    Double saldo;
    Set<OperationDto> operationDto;


    @java.lang.SuppressWarnings("all")
    public static abstract class ContoDtoBuilder<C extends ContoDto, B extends ContoDto.ContoDtoBuilder<C, B>> {
        @java.lang.SuppressWarnings("all")
        private Integer id;
        @java.lang.SuppressWarnings("all")
        private UserDto userDto;
        @java.lang.SuppressWarnings("all")
        private Double saldo;
        @java.lang.SuppressWarnings("all")
        private Set<OperationDto> operationDto;

        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.SuppressWarnings("all")
        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B id(final Integer id) {
            this.id = id;
            return self();
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B userDto(final UserDto userDto) {
            this.userDto = userDto;
            return self();
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B saldo(final Double saldo) {
            this.saldo = saldo;
            return self();
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B operationDto(final Set<OperationDto> operationDto) {
            this.operationDto = operationDto;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ContoDto.ContoDtoBuilder(id=" + this.id + ", userDto=" + this.userDto + ", saldo=" + this.saldo + ", operationDto=" + this.operationDto + ")";
        }
    }


    @java.lang.SuppressWarnings("all")
    private static final class ContoDtoBuilderImpl extends ContoDto.ContoDtoBuilder<ContoDto, ContoDto.ContoDtoBuilderImpl> {
        @java.lang.SuppressWarnings("all")
        private ContoDtoBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected ContoDto.ContoDtoBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public ContoDto build() {
            return new ContoDto(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    protected ContoDto(final ContoDto.ContoDtoBuilder<?, ?> b) {
        this.id = b.id;
        this.userDto = b.userDto;
        this.saldo = b.saldo;
        this.operationDto = b.operationDto;
    }

    @java.lang.SuppressWarnings("all")
    public static ContoDto.ContoDtoBuilder<?, ?> builder() {
        return new ContoDto.ContoDtoBuilderImpl();
    }

    @java.lang.SuppressWarnings("all")
    public Integer getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public UserDto getUserDto() {
        return this.userDto;
    }

    @java.lang.SuppressWarnings("all")
    public Double getSaldo() {
        return this.saldo;
    }

    @java.lang.SuppressWarnings("all")
    public Set<OperationDto> getOperationDto() {
        return this.operationDto;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Integer id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserDto(final UserDto userDto) {
        this.userDto = userDto;
    }

    @java.lang.SuppressWarnings("all")
    public void setSaldo(final Double saldo) {
        this.saldo = saldo;
    }

    @java.lang.SuppressWarnings("all")
    public void setOperationDto(final Set<OperationDto> operationDto) {
        this.operationDto = operationDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ContoDto)) return false;
        final ContoDto other = (ContoDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$saldo = this.getSaldo();
        final java.lang.Object other$saldo = other.getSaldo();
        if (this$saldo == null ? other$saldo != null : !this$saldo.equals(other$saldo)) return false;
        final java.lang.Object this$userDto = this.getUserDto();
        final java.lang.Object other$userDto = other.getUserDto();
        if (this$userDto == null ? other$userDto != null : !this$userDto.equals(other$userDto)) return false;
        final java.lang.Object this$operationDto = this.getOperationDto();
        final java.lang.Object other$operationDto = other.getOperationDto();
        if (this$operationDto == null ? other$operationDto != null : !this$operationDto.equals(other$operationDto)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ContoDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $saldo = this.getSaldo();
        result = result * PRIME + ($saldo == null ? 43 : $saldo.hashCode());
        final java.lang.Object $userDto = this.getUserDto();
        result = result * PRIME + ($userDto == null ? 43 : $userDto.hashCode());
        final java.lang.Object $operationDto = this.getOperationDto();
        result = result * PRIME + ($operationDto == null ? 43 : $operationDto.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public ContoDto(final Integer id, final UserDto userDto, final Double saldo, final Set<OperationDto> operationDto) {
        this.id = id;
        this.userDto = userDto;
        this.saldo = saldo;
        this.operationDto = operationDto;
    }

    @java.lang.SuppressWarnings("all")
    public ContoDto() {
    }
}
