// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.dto;

import lombok.Builder;

public class UserGiuridicoDto extends UserDto {
     String partitaIva;


     @java.lang.SuppressWarnings("all")
     public static abstract class UserGiuridicoDtoBuilder<C extends UserGiuridicoDto, B extends UserGiuridicoDto.UserGiuridicoDtoBuilder<C, B>> extends UserDto.UserDtoBuilder<C, B> {
          @java.lang.SuppressWarnings("all")
          private String partitaIva;

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          protected abstract B self();

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          public abstract C build();

          /**
           * @return {@code this}.
           */
          @java.lang.SuppressWarnings("all")
          public B partitaIva(final String partitaIva) {
               this.partitaIva = partitaIva;
               return self();
          }

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          public java.lang.String toString() {
               return "UserGiuridicoDto.UserGiuridicoDtoBuilder(super=" + super.toString() + ", partitaIva=" + this.partitaIva + ")";
          }
     }


     @java.lang.SuppressWarnings("all")
     private static final class UserGiuridicoDtoBuilderImpl extends UserGiuridicoDto.UserGiuridicoDtoBuilder<UserGiuridicoDto, UserGiuridicoDto.UserGiuridicoDtoBuilderImpl> {
          @java.lang.SuppressWarnings("all")
          private UserGiuridicoDtoBuilderImpl() {
          }

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          protected UserGiuridicoDto.UserGiuridicoDtoBuilderImpl self() {
               return this;
          }

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          public UserGiuridicoDto build() {
               return new UserGiuridicoDto(this);
          }
     }

     @java.lang.SuppressWarnings("all")
     protected UserGiuridicoDto(final UserGiuridicoDto.UserGiuridicoDtoBuilder<?, ?> b) {
          super(b);
          this.partitaIva = b.partitaIva;
     }

     @java.lang.SuppressWarnings("all")
     public static UserGiuridicoDto.UserGiuridicoDtoBuilder<?, ?> builder() {
          return new UserGiuridicoDto.UserGiuridicoDtoBuilderImpl();
     }

     @java.lang.SuppressWarnings("all")
     public UserGiuridicoDto(final String partitaIva) {
          this.partitaIva = partitaIva;
     }

     @java.lang.SuppressWarnings("all")
     public UserGiuridicoDto() {
     }

     @java.lang.SuppressWarnings("all")
     public String getPartitaIva() {
          return this.partitaIva;
     }

     @java.lang.SuppressWarnings("all")
     public void setPartitaIva(final String partitaIva) {
          this.partitaIva = partitaIva;
     }

     @java.lang.Override
     @java.lang.SuppressWarnings("all")
     public boolean equals(final java.lang.Object o) {
          if (o == this) return true;
          if (!(o instanceof UserGiuridicoDto)) return false;
          final UserGiuridicoDto other = (UserGiuridicoDto) o;
          if (!other.canEqual((java.lang.Object) this)) return false;
          if (!super.equals(o)) return false;
          final java.lang.Object this$partitaIva = this.getPartitaIva();
          final java.lang.Object other$partitaIva = other.getPartitaIva();
          if (this$partitaIva == null ? other$partitaIva != null : !this$partitaIva.equals(other$partitaIva)) return false;
          return true;
     }

     @java.lang.SuppressWarnings("all")
     protected boolean canEqual(final java.lang.Object other) {
          return other instanceof UserGiuridicoDto;
     }

     @java.lang.Override
     @java.lang.SuppressWarnings("all")
     public int hashCode() {
          final int PRIME = 59;
          int result = super.hashCode();
          final java.lang.Object $partitaIva = this.getPartitaIva();
          result = result * PRIME + ($partitaIva == null ? 43 : $partitaIva.hashCode());
          return result;
     }
}
