// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.dto;

public class UserFisicoDto extends UserDto {
     String codiceFiscale;


     @java.lang.SuppressWarnings("all")
     public static abstract class UserFisicoDtoBuilder<C extends UserFisicoDto, B extends UserFisicoDto.UserFisicoDtoBuilder<C, B>> extends UserDto.UserDtoBuilder<C, B> {
          @java.lang.SuppressWarnings("all")
          private String codiceFiscale;

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          protected abstract B self();

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          public abstract C build();

          /**
           * @return {@code this}.
           */
          @java.lang.SuppressWarnings("all")
          public B codiceFiscale(final String codiceFiscale) {
               this.codiceFiscale = codiceFiscale;
               return self();
          }

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          public java.lang.String toString() {
               return "UserFisicoDto.UserFisicoDtoBuilder(super=" + super.toString() + ", codiceFiscale=" + this.codiceFiscale + ")";
          }
     }


     @java.lang.SuppressWarnings("all")
     private static final class UserFisicoDtoBuilderImpl extends UserFisicoDto.UserFisicoDtoBuilder<UserFisicoDto, UserFisicoDto.UserFisicoDtoBuilderImpl> {
          @java.lang.SuppressWarnings("all")
          private UserFisicoDtoBuilderImpl() {
          }

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          protected UserFisicoDto.UserFisicoDtoBuilderImpl self() {
               return this;
          }

          @java.lang.Override
          @java.lang.SuppressWarnings("all")
          public UserFisicoDto build() {
               return new UserFisicoDto(this);
          }
     }

     @java.lang.SuppressWarnings("all")
     protected UserFisicoDto(final UserFisicoDto.UserFisicoDtoBuilder<?, ?> b) {
          super(b);
          this.codiceFiscale = b.codiceFiscale;
     }

     @java.lang.SuppressWarnings("all")
     public static UserFisicoDto.UserFisicoDtoBuilder<?, ?> builder() {
          return new UserFisicoDto.UserFisicoDtoBuilderImpl();
     }

     @java.lang.SuppressWarnings("all")
     public UserFisicoDto(final String codiceFiscale) {
          this.codiceFiscale = codiceFiscale;
     }

     @java.lang.SuppressWarnings("all")
     public UserFisicoDto() {
     }

     @java.lang.Override
     @java.lang.SuppressWarnings("all")
     public boolean equals(final java.lang.Object o) {
          if (o == this) return true;
          if (!(o instanceof UserFisicoDto)) return false;
          final UserFisicoDto other = (UserFisicoDto) o;
          if (!other.canEqual((java.lang.Object) this)) return false;
          if (!super.equals(o)) return false;
          final java.lang.Object this$codiceFiscale = this.getCodiceFiscale();
          final java.lang.Object other$codiceFiscale = other.getCodiceFiscale();
          if (this$codiceFiscale == null ? other$codiceFiscale != null : !this$codiceFiscale.equals(other$codiceFiscale)) return false;
          return true;
     }

     @java.lang.SuppressWarnings("all")
     protected boolean canEqual(final java.lang.Object other) {
          return other instanceof UserFisicoDto;
     }

     @java.lang.Override
     @java.lang.SuppressWarnings("all")
     public int hashCode() {
          final int PRIME = 59;
          int result = super.hashCode();
          final java.lang.Object $codiceFiscale = this.getCodiceFiscale();
          result = result * PRIME + ($codiceFiscale == null ? 43 : $codiceFiscale.hashCode());
          return result;
     }

     @java.lang.SuppressWarnings("all")
     public String getCodiceFiscale() {
          return this.codiceFiscale;
     }

     @java.lang.SuppressWarnings("all")
     public void setCodiceFiscale(final String codiceFiscale) {
          this.codiceFiscale = codiceFiscale;
     }
}
