// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.entities;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity
public class ContoPaypal extends Conto {
    @Column(name = "cartadicredito")
    String cartaDiCredito;


    @java.lang.SuppressWarnings("all")
    public static abstract class ContoPaypalBuilder<C extends ContoPaypal, B extends ContoPaypal.ContoPaypalBuilder<C, B>> extends Conto.ContoBuilder<C, B> {
        @java.lang.SuppressWarnings("all")
        private String cartaDiCredito;

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B cartaDiCredito(final String cartaDiCredito) {
            this.cartaDiCredito = cartaDiCredito;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ContoPaypal.ContoPaypalBuilder(super=" + super.toString() + ", cartaDiCredito=" + this.cartaDiCredito + ")";
        }
    }


    @java.lang.SuppressWarnings("all")
    private static final class ContoPaypalBuilderImpl extends ContoPaypal.ContoPaypalBuilder<ContoPaypal, ContoPaypal.ContoPaypalBuilderImpl> {
        @java.lang.SuppressWarnings("all")
        private ContoPaypalBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected ContoPaypal.ContoPaypalBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public ContoPaypal build() {
            return new ContoPaypal(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    protected ContoPaypal(final ContoPaypal.ContoPaypalBuilder<?, ?> b) {
        super(b);
        this.cartaDiCredito = b.cartaDiCredito;
    }

    @java.lang.SuppressWarnings("all")
    public static ContoPaypal.ContoPaypalBuilder<?, ?> builder() {
        return new ContoPaypal.ContoPaypalBuilderImpl();
    }

    @java.lang.SuppressWarnings("all")
    public ContoPaypal(final String cartaDiCredito) {
        this.cartaDiCredito = cartaDiCredito;
    }

    @java.lang.SuppressWarnings("all")
    public ContoPaypal() {
    }

    @java.lang.SuppressWarnings("all")
    public String getCartaDiCredito() {
        return this.cartaDiCredito;
    }

    @java.lang.SuppressWarnings("all")
    public void setCartaDiCredito(final String cartaDiCredito) {
        this.cartaDiCredito = cartaDiCredito;
    }
}
