// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.entities;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity
public class ContoBanca extends Conto {
    @Column(name = "iban")
    String iban;


    @java.lang.SuppressWarnings("all")
    public static abstract class ContoBancaBuilder<C extends ContoBanca, B extends ContoBanca.ContoBancaBuilder<C, B>> extends Conto.ContoBuilder<C, B> {
        @java.lang.SuppressWarnings("all")
        private String iban;

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B iban(final String iban) {
            this.iban = iban;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ContoBanca.ContoBancaBuilder(super=" + super.toString() + ", iban=" + this.iban + ")";
        }
    }


    @java.lang.SuppressWarnings("all")
    private static final class ContoBancaBuilderImpl extends ContoBanca.ContoBancaBuilder<ContoBanca, ContoBanca.ContoBancaBuilderImpl> {
        @java.lang.SuppressWarnings("all")
        private ContoBancaBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected ContoBanca.ContoBancaBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public ContoBanca build() {
            return new ContoBanca(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    protected ContoBanca(final ContoBanca.ContoBancaBuilder<?, ?> b) {
        super(b);
        this.iban = b.iban;
    }

    @java.lang.SuppressWarnings("all")
    public static ContoBanca.ContoBancaBuilder<?, ?> builder() {
        return new ContoBanca.ContoBancaBuilderImpl();
    }

    @java.lang.SuppressWarnings("all")
    public ContoBanca(final String iban) {
        this.iban = iban;
    }

    @java.lang.SuppressWarnings("all")
    public ContoBanca() {
    }

    @java.lang.SuppressWarnings("all")
    public String getIban() {
        return this.iban;
    }

    @java.lang.SuppressWarnings("all")
    public void setIban(final String iban) {
        this.iban = iban;
    }
}
