// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.entities;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity
public class ContoBorsellino extends Conto {
    @Column(name = "meccanismodiapertura")
    Boolean meccanismoDiApertura;


    @java.lang.SuppressWarnings("all")
    public static abstract class ContoBorsellinoBuilder<C extends ContoBorsellino, B extends ContoBorsellino.ContoBorsellinoBuilder<C, B>> extends Conto.ContoBuilder<C, B> {
        @java.lang.SuppressWarnings("all")
        private Boolean meccanismoDiApertura;

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B meccanismoDiApertura(final Boolean meccanismoDiApertura) {
            this.meccanismoDiApertura = meccanismoDiApertura;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ContoBorsellino.ContoBorsellinoBuilder(super=" + super.toString() + ", meccanismoDiApertura=" + this.meccanismoDiApertura + ")";
        }
    }


    @java.lang.SuppressWarnings("all")
    private static final class ContoBorsellinoBuilderImpl extends ContoBorsellino.ContoBorsellinoBuilder<ContoBorsellino, ContoBorsellino.ContoBorsellinoBuilderImpl> {
        @java.lang.SuppressWarnings("all")
        private ContoBorsellinoBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected ContoBorsellino.ContoBorsellinoBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public ContoBorsellino build() {
            return new ContoBorsellino(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    protected ContoBorsellino(final ContoBorsellino.ContoBorsellinoBuilder<?, ?> b) {
        super(b);
        this.meccanismoDiApertura = b.meccanismoDiApertura;
    }

    @java.lang.SuppressWarnings("all")
    public static ContoBorsellino.ContoBorsellinoBuilder<?, ?> builder() {
        return new ContoBorsellino.ContoBorsellinoBuilderImpl();
    }

    @java.lang.SuppressWarnings("all")
    public ContoBorsellino(final Boolean meccanismoDiApertura) {
        this.meccanismoDiApertura = meccanismoDiApertura;
    }

    @java.lang.SuppressWarnings("all")
    public ContoBorsellino() {
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getMeccanismoDiApertura() {
        return this.meccanismoDiApertura;
    }

    @java.lang.SuppressWarnings("all")
    public void setMeccanismoDiApertura(final Boolean meccanismoDiApertura) {
        this.meccanismoDiApertura = meccanismoDiApertura;
    }
}
