// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity
@Table(name = "operations")
public class Operation {
   @Id
   @NotNull
   @Column(name = "operationid")
   private Integer id;
   @JsonBackReference
   @ManyToOne
   @JoinColumn(name = "contoid")
   private Conto conto;
   @NotNull(message = "inserire il valore")
   @Column(name = "ammontare")
   private Double ammontare;

   @java.lang.SuppressWarnings("all")
   public void setId(@NotNull final Integer id) {
      this.id = id;
   }

   @java.lang.SuppressWarnings("all")
   public void setConto(final Conto conto) {
      this.conto = conto;
   }

   @java.lang.SuppressWarnings("all")
   public void setAmmontare(@NotNull(message = "inserire il valore") final Double ammontare) {
      this.ammontare = ammontare;
   }

   @NotNull
   @java.lang.SuppressWarnings("all")
   public Integer getId() {
      return this.id;
   }

   @java.lang.SuppressWarnings("all")
   public Conto getConto() {
      return this.conto;
   }

   @NotNull(message = "inserire il valore")
   @java.lang.SuppressWarnings("all")
   public Double getAmmontare() {
      return this.ammontare;
   }

   @java.lang.SuppressWarnings("all")
   public Operation(@NotNull final Integer id, final Conto conto, @NotNull(message = "inserire il valore") final Double ammontare) {
      this.id = id;
      this.conto = conto;
      this.ammontare = ammontare;
   }

   @java.lang.SuppressWarnings("all")
   public Operation() {
   }
}
