// Generated by delombok at Thu Jan 05 09:42:45 CET 2023
package contocorrente.conto.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
// @Table(name = "userfisici", schema = "public")
@Entity
public class UserFisico extends Users {
    @Column(name = "codicefiscale")
    private String codiceFiscale;


    @java.lang.SuppressWarnings("all")
    public static abstract class UserFisicoBuilder<C extends UserFisico, B extends UserFisico.UserFisicoBuilder<C, B>> extends Users.UsersBuilder<C, B> {
        @java.lang.SuppressWarnings("all")
        private String codiceFiscale;

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public abstract C build();

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public B codiceFiscale(final String codiceFiscale) {
            this.codiceFiscale = codiceFiscale;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "UserFisico.UserFisicoBuilder(super=" + super.toString() + ", codiceFiscale=" + this.codiceFiscale + ")";
        }
    }


    @java.lang.SuppressWarnings("all")
    private static final class UserFisicoBuilderImpl extends UserFisico.UserFisicoBuilder<UserFisico, UserFisico.UserFisicoBuilderImpl> {
        @java.lang.SuppressWarnings("all")
        private UserFisicoBuilderImpl() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        protected UserFisico.UserFisicoBuilderImpl self() {
            return this;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public UserFisico build() {
            return new UserFisico(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    protected UserFisico(final UserFisico.UserFisicoBuilder<?, ?> b) {
        super(b);
        this.codiceFiscale = b.codiceFiscale;
    }

    @java.lang.SuppressWarnings("all")
    public static UserFisico.UserFisicoBuilder<?, ?> builder() {
        return new UserFisico.UserFisicoBuilderImpl();
    }

    @java.lang.SuppressWarnings("all")
    public String getCodiceFiscale() {
        return this.codiceFiscale;
    }

    @java.lang.SuppressWarnings("all")
    public void setCodiceFiscale(final String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    @java.lang.SuppressWarnings("all")
    public UserFisico() {
    }

    @java.lang.SuppressWarnings("all")
    public UserFisico(final String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }
}
